services:
  rag-api:
    build: ./rag-api
    ports:
      - "8000:8000"
    volumes:
      - ./rag-api:/app
    depends_on:
      milvus:
        condition: service_healthy
    env_file:
      - ./rag-api/.env
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  rag-ui:
    build: ./rag-ui
    ports:
      - "3000:80"
    depends_on:
      - rag-api
    volumes:
      - ./rag-ui:/app
    environment:
      - REACT_APP_API_URL=/api
      # No API key needed for frontend - uses secure backend proxy

  milvus:
    image: "milvusdb/milvus:v2.3.9"
    command: "milvus run standalone"
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 90s
    volumes:
      - ./milvus_db/milvus:/var/lib/milvus:rw
      - ./milvus_db/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml:rw